Pull upsteam only args into a conditional.
quipucords/qpc-tools pull request #35
Opened 2019-10-11 18:59 UTC by myersCody

2019-10-15 18:55 UTC, kholdaway requested changes
Version is applicable to both up and downstream.

2019-10-15 18:55 UTC, kholdaway commented on qpc_tools/cli/install.py
> +            self.parser.add_argument('--version', dest='cli_version',
Let's pull this out since it applies to both upstream and downstream.

2019-10-15 18:55 UTC, kholdaway commented on qpc_tools/server/install.py
> +            self.parser.add_argument('--version', dest='server_version',
Let's pull this out since it applies to both upstream and downstream.

2019-10-16 14:31 UTC, abaiken approved these changes
Nice work!

2019-10-16 17:08 UTC, kholdaway approved these changes

2019-10-16 17:43 UTC, merged