WIP: Add vars upstream to make downstream transition easier
quipucords/qpc-tools pull request #40
Opened 2019-10-17 19:53 UTC by myersCody

## Test that you can change the extra vars that I added:

-------
### Testing cli_package_name playbook var

```
qpc-tools cli install --advanced cli_package_name=itscodynotcory.el7.rpm
```

⚠️ You should see No RPM file matching 'itscodynotcory.el7.rpm' found on system. You could also test this by passing in another package that you want installed like wget. 

-------
### Testing cli_package_name playbook var (offline)
```
mv /qpc_tools/install/qpc.el6.noarch.rpm /qpc_tools/install/cody.rpm
qpc-tools cli install --offline --offline-files /qpc_tools/install/packages --advanced cli_package_name='cody.rpm'
```
-------
### Testing server_image_name & version var online
```
qpc-tools server install --advanced server_image_name=quipucords2 server_image_tag=latest
```
⚠️ It is going to fail because the release version won't match the server_image_name & server_image_tag. 😬 
-------
### Testing server_image_name & version var offline
```
# From host make file: 
make local-server-image server_version=latest image_name=quipucords2
qpc-tools server install --advanced server_image_name=quipucords2 server_image_tag=latest --offline --offline-files /qpc_tools/install/packages
```

2019-10-18 21:19 UTC, abaiken commented on README.md
> +Sometimes flags that are not externally available will need to be flipped in order to bypass special case issues during SEAP engagements. For example, some customers may not be able to use supervisor
change arguements - arguments

2019-10-18 21:45 UTC, kholdaway requested changes

2019-10-18 21:45 UTC, kholdaway commented on qpc_tools/server/ansible/install/roles/server/tasks/init_vars_online.yml
> +    - server_image_tag == ""
Revert this and downstream replace file.

2019-10-18 21:45 UTC, kholdaway commented on qpc_tools/cli/ansible/install/roles/cli/tasks/load_rpm_online.yml
> +    name: '{{ cli_package_name }}'
Revert this and replace this whole file downstream with a small role that does a simple yum install.

2019-10-18 21:45 UTC, kholdaway commented on qpc_tools/cli/ansible/install/roles/cli/tasks/init_vars_offline.yml
> +- name: Set the Quipucords CLI RPM package name
Move this back to init_vars.yml

2019-10-21 19:39 UTC, abaiken approved these changes
Looks good 😄

2019-10-21 19:40 UTC, abaiken commented on qpc_tools/cli/install.py
> +                                 nargs='+', default=[],
Nice fix!

2019-10-21 19:59 UTC, kholdaway approved these changes

2019-10-21 20:03 UTC, merged